# Generated by Django 5.0.6 on 2024-06-24 01:44

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela',
            name='descricao',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabela',
            name='fim_data',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='tabela',
            name='inicio_data',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='tabela',
            name='responsavel',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabela',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
