# Generated by Django 5.0.6 on 2024-07-03 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_app', '0002_tabela_descricao_tabela_fim_data_tabela_inicio_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela',
            name='projeto',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tabela',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='fase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='fim_data',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='inicio_data',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='responsavel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
