# Generated by Django 5.0.6 on 2024-07-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_app', '0003_tabela_projeto_alter_tabela_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela',
            name='descricao',
            field=models.CharField(blank=True, default='novo', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='fase',
            field=models.CharField(blank=True, default='novo', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='projeto',
            field=models.CharField(default='Projeto', max_length=20),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='responsavel',
            field=models.CharField(blank=True, default='novo', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='status',
            field=models.CharField(blank=True, default='novo', max_length=10, null=True),
        ),
    ]
